# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20170504_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
